const BASE="https://api.helius.xyz/v0";
const TIMEOUT=15000;
async function get(path){const key=process.env.HELIUS_API_KEY;if(!key)throw new Error("HELIUS_API_KEY is not configured");const r=await fetch(`${BASE}${path}${path.includes("?")?"&":"?"}api-key=${encodeURIComponent(key)}`,{signal:AbortSignal.timeout?AbortSignal.timeout(TIMEOUT):undefined});if(!r.ok)throw new Error(`Helius HTTP ${r.status}`);return r.json();}
export function validateSolanaAddress(a){return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(a);}
export async function analyzeSolanaAddress(address){
 const txs=await get(`/addresses/${address}/transactions?limit=100`); const rows=Array.isArray(txs)?txs:[]; const peers=new Map();let incoming=0,outgoing=0;const assets=new Map([["SOL",true]]);
 for(const t of rows){for(const x of (t?.nativeTransfers||[])){const from=x?.fromUserAccount,to=x?.toUserAccount;if(from===address)outgoing++;if(to===address)incoming++;const peer=from===address?to:to===address?from:null;if(peer){const p=peers.get(peer)||{address:peer,incoming:0,outgoing:0,transfers:0,assets:[]};p[from===address?"outgoing":"incoming"]++;p.transfers++;peers.set(peer,p);}}for(const x of (t?.tokenTransfers||[])){if(x?.mint)assets.set(x.mint,true);const from=x?.fromUserAccount,to=x?.toUserAccount;const peer=from===address?to:to===address?from:null;if(peer){const p=peers.get(peer)||{address:peer,incoming:0,outgoing:0,transfers:0,assets:[]};p[from===address?"outgoing":"incoming"]++;p.transfers++;peers.set(peer,p);}}}
 const times=rows.map(t=>Number(t?.timestamp||0)).filter(Boolean); const nativeVolume=rows.reduce((s,t)=>s+(t?.nativeTransfers||[]).reduce((a,x)=>a+Math.abs(Number(x?.amount||0))/1e9,0),0);
 return {behavior:{transaction_count:rows.length,incoming_count:incoming,outgoing_count:outgoing,first_seen:times.length?new Date(Math.min(...times)*1000).toISOString():null,last_seen:times.length?new Date(Math.max(...times)*1000).toISOString():null,volume_native:nativeVolume,native_balance:null,native_symbol:"SOL",contract_counterparties:0},assets:[...assets.keys()].slice(0,100).map(symbol=>({symbol})),recent_operations:rows.slice(0,50).map(t=>({hash:t.signature||null,type:t.type||null,timestamp:t.timestamp?new Date(t.timestamp*1000).toISOString():null})),counterparties:[...peers.values()].sort((a,b)=>b.transfers-a.transfers).slice(0,50),sources:[{name:"Helius",checked_at:new Date().toISOString()}]};
}
