const BASE="https://api.trongrid.io";
const TIMEOUT=12000;
async function get(path){const h={Accept:"application/json"};if(process.env.TRONGRID_API_KEY)h["TRON-PRO-API-KEY"]=process.env.TRONGRID_API_KEY;const r=await fetch(`${BASE}${path}`,{headers:h,signal:AbortSignal.timeout?AbortSignal.timeout(TIMEOUT):undefined});if(!r.ok)throw new Error(`TronGrid HTTP ${r.status}`);return r.json();}
export function validateTronAddress(a){return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(a);}
export async function analyzeTronAddress(address){
 const [acct,txs,trc20]=await Promise.all([get(`/v1/accounts/${address}`),get(`/v1/accounts/${address}/transactions?limit=200&only_confirmed=true&order_by=block_timestamp,desc`),get(`/v1/accounts/${address}/transactions/trc20?limit=200&only_confirmed=true&order_by=block_timestamp,desc`)]);
 const native=Number(acct?.data?.[0]?.balance||0)/1e6; const rows=[...(Array.isArray(txs?.data)?txs.data:[]),...(Array.isArray(trc20?.data)?trc20.data:[])]; const times=rows.map(x=>Number(x?.block_timestamp||0)).filter(Boolean);
 const peers=new Map(); let incoming=0,outgoing=0; for(const t of rows){const tr=t?.token_info?true:false;const from=t?.from||t?.raw_data?.contract?.[0]?.parameter?.value?.owner_address;const to=t?.to||t?.raw_data?.contract?.[0]?.parameter?.value?.to_address;if(from===address)outgoing++;if(to===address)incoming++;const peer=from===address?to:to===address?from:null;if(peer){const x=peers.get(peer)||{address:peer,incoming:0,outgoing:0,transfers:0,assets:[]};x[from===address?"outgoing":"incoming"]++;x.transfers++;if(t?.token_info?.symbol&&!x.assets.includes(t.token_info.symbol))x.assets.push(t.token_info.symbol);peers.set(peer,x);}}
 const assets=new Map();for(const t of trc20?.data||[]){const s=t?.token_info?.symbol;if(s)assets.set(s,true);} assets.set("TRX",true);
 return {behavior:{transaction_count:rows.length,incoming_count:incoming,outgoing_count:outgoing,first_seen:times.length?new Date(Math.min(...times)).toISOString():null,last_seen:times.length?new Date(Math.max(...times)).toISOString():null,volume_native:native,native_balance:native,native_symbol:"TRX",contract_counterparties:0},assets:[...assets.keys()].slice(0,100).map(symbol=>({symbol})),recent_operations:rows.slice(0,50).map(t=>({hash:t.txID||t.transaction_id||null,direction:(t.from||"")===address?"outgoing":"incoming",asset:t?.token_info?.symbol||"TRX",timestamp:t.block_timestamp?new Date(t.block_timestamp).toISOString():null})),counterparties:[...peers.values()].sort((a,b)=>b.transfers-a.transfers).slice(0,50),sources:[{name:"TronGrid",checked_at:new Date().toISOString()}]};
}
